# Generated by Django 4.2.11 on 2024-04-15 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_myuser_client_status_alter_client_acc_num_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='UserProfile',
        ),
    ]
