# Generated by Django 4.2.11 on 2024-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_myuser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(default='Иванов Иван Иванович', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='acc_num',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='fam',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='otc',
            field=models.CharField(max_length=128),
        ),
    ]
