# Generated by Django 4.2.11 on 2024-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_userprofile_fio_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='midlle_name',
            field=models.CharField(default='Иванович', max_length=128),
        ),
    ]
